#' Bind logical dbt sources to exact published lake releases
#'
#' Use successful ingestion or product results from any lake layer as ordinary
#' dbt sources. Each source group must use one physical schema. Bind additional
#' groups with separate calls, for example `name = "raw"` and `name = "enriched"`.
#' The registry supplies exact physical names and verifies the recorded run;
#' editable result output descriptions are never used as relation authority.
#'
#' For `dr_dbt_project(lake = config)`, this function updates a deferred
#' specification. No database is opened and no files are written. At execution,
#' all groups are resolved and validated before one package-owned source YAML
#' is replaced. Constructor `sources` uses the group name `inputs`.
#'
#' For an externally configured project, this is an explicit immediate YAML
#' generator. It preserves other logical tables in the same generated group.
#' Only a file with the package ownership marker can be replaced. Its profile
#' must attach the same catalog as `lake`. Both modes use the first literal
#' `model-paths` directory, defaulting to `models`, and never write data or views.
#' Coordinate concurrent project writers and close caller-owned lake handles
#' before dbt execution.
#'
#' @param project A [dr_dbt_project()] specification.
#' @param sources Named, non-empty list of successful `dr_run_result` objects
#'   returned by [dataraft.lake::dr_ingest()] or [dataraft.core::dr_publish()]. Names are dbt identifiers such as `orders`.
#' @param name Logical dbt source name, used by `source(name, table)` in SQL.
#' @returns The project specification, invisibly, for use in a pipe.
#' @seealso [dr_dbt_init()], [dr_dbt_contract()]
#' @examplesIf requireNamespace("duckdb", quietly = TRUE) && requireNamespace("yaml", quietly = TRUE)
#' root <- tempfile("dataraft-dbt-sources-")
#' config <- dataraft.lake::dr_lake_config(
#'   dataraft.lake::dr_registry_duckdb(file.path(root, "lake.db")),
#'   dataraft.lake::dr_storage_local(file.path(root, "data")),
#'   landing = file.path(root, "landing"), backend = "duckdb",
#'   layers = c("raw", "staging", "core", "marts")
#' )
#' accepted <- dataraft.lake::dr_ingest(data.frame(
#'   order_id = 1:2, customer_id = c(1L, 1L), amount = c(10, 20)
#' ), name = "orders", to = config)
#' project <- dr_dbt_init(file.path(root, "dbt"), config,
#'   sources = list(orders = accepted))
#' dr_dbt_sources(project, list(orders = accepted), name = "raw")
#' unlink(root, recursive = TRUE)
#' @export
dr_dbt_sources <- function(project, sources, name = "inputs") {
  if (!inherits(project, "dr_dbt_project")) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "Use dr_dbt_project() or dr_dbt_init() first.",
      "dr_dbt_invalid"
    )
  }
  dataraft.core::ident(name)
  references <- dbt_source_references(sources)
  expected <- project$lake %||% project$source_config
  dbt_source_catalog(references, expected)
  if (!is.null(project$lake)) {
    previous <- project$source_groups[[name]] %||% list()
    project$source_groups[[name]] <- c(
      previous[!names(previous) %in% names(references)],
      references
    )
    return(invisible(project))
  }
  dataraft.core::need("yaml")
  binding <- dbt_source_binding(sources, name, expected)
  if (!file.exists(file.path(project$path, "dbt_project.yml"))) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "No dbt_project.yml found in the project.",
      "dr_dbt_invalid"
    )
  }
  if (!is.null(project$source_config)) {
    expected <- dbt_catalog_fingerprint(project$source_config)
    if (!identical(binding$config$meta$dataraft$catalog, expected)) {
      dataraft.core::abort(
        subclass = "dataraft_error_dbt",
        "Sources belong to a different project catalog.",
        "dr_dbt_invalid"
      )
    }
  }
  directory <- dbt_models_directory(project)
  destination <- file.path(
    directory,
    paste0("dataraft_sources_", name, ".yml")
  )
  marker <- "# Generated by dr_dbt_sources."
  if (file.exists(destination)) {
    if (!identical(readLines(destination, n = 1L, warn = FALSE), marker)) {
      dataraft.core::abort(
        subclass = "dataraft_error_dbt",
        "The source YAML is not package-owned; choose another source name.",
        "dr_dbt_invalid"
      )
    }
    previous <- tryCatch(yaml::read_yaml(destination), error = identity)
    old <- if (is.list(previous) && length(previous$sources) == 1L) {
      previous$sources[[1L]]
    } else {
      NULL
    }
    if (
      !is.list(old) ||
        !identical(old$name, name) ||
        !is.list(old$tables) ||
        !identical(old$database, binding$database) ||
        !identical(old$schema, binding$schema) ||
        !identical(
          old$config$meta$dataraft$catalog,
          binding$config$meta$dataraft$catalog
        )
    ) {
      dataraft.core::abort(
        subclass = "dataraft_error_dbt",
        "Existing source YAML is invalid or belongs to another catalog.",
        "dr_dbt_invalid"
      )
    }
    old_names <- vapply(
      old$tables,
      function(table) {
        if (
          !is.list(table) ||
            !is.character(table$name) ||
            length(table$name) != 1L ||
            is.na(table$name)
        ) {
          return(NA_character_)
        }
        table$name
      },
      character(1)
    )
    if (anyNA(old_names) || anyDuplicated(old_names)) {
      dataraft.core::abort(
        subclass = "dataraft_error_dbt",
        "Existing source YAML contains invalid table names.",
        "dr_dbt_invalid"
      )
    }
    new_names <- vapply(binding$tables, `[[`, character(1), "name")
    binding$tables <- c(old$tables[!old_names %in% new_names], binding$tables)
  }
  content <- paste0(
    marker,
    "\n",
    yaml::as.yaml(list(
      version = 2L,
      sources = list(binding)
    ))
  )
  if (
    !dir.exists(directory) &&
      !dir.create(directory, recursive = TRUE, showWarnings = FALSE)
  ) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "Cannot create the dbt models directory.",
      "dr_dbt_io"
    )
  }
  temporary <- tempfile(".dataraft-sources-", tmpdir = directory)
  on.exit(unlink(temporary), add = TRUE)
  writeLines(content, temporary, useBytes = TRUE)
  if (!suppressWarnings(file.rename(temporary, destination))) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "Could not replace source YAML; the previous file was preserved.",
      "dr_dbt_io"
    )
  }
  invisible(project)
}


dbt_catalog_fingerprint <- function(config) {
  rlang::local_error_call(rlang::caller_env())
  if (!inherits(config, "dr_config")) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "A published release must retain its lake configuration.",
      "dr_dbt_invalid"
    )
  }
  dataraft.core::fingerprint(list(
    backend = config$backend,
    catalog = config$catalog,
    storage = if (identical(config$backend, "ducklake")) {
      config$storage
    } else {
      NULL
    }
  ))
}


# Normalize only identity and connection-free configuration, never input rows.
#' Extension implementation helper
#'
#' Internal implementation interface for the DataRaft package family.
#' @usage NULL
#' @keywords internal
#' @export
#' @name dbt_source_references

dbt_source_references <- function(sources) {
  rlang::local_error_call(rlang::caller_env())
  if (
    !is.list(sources) ||
      !length(sources) ||
      is.null(names(sources)) ||
      anyNA(names(sources)) ||
      anyDuplicated(names(sources)) ||
      any(!nzchar(names(sources)))
  ) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "sources must be a named, non-empty list of published lake results.",
      "dr_dbt_invalid"
    )
  }
  invisible(lapply(names(sources), dataraft.core::ident))
  lapply(sources, function(result) {
    valid_scalar <- function(x) {
      rlang::local_error_call(rlang::caller_env())
      is.character(x) && length(x) == 1L && !is.na(x) && nzchar(x)
    }
    fields <- c("asset", "release_id", "run_id", "status")
    if (
      !inherits(result, "dr_run_result") ||
        !all(vapply(result[fields], valid_scalar, logical(1))) ||
        !result$status %in% c("published", "cached") ||
        !inherits(result$output_config, "dr_config")
    ) {
      dataraft.core::abort(
        subclass = "dataraft_error_dbt",
        "Each source needs a successful immutable lake release, with its asset, release, run and configuration.",
        "dr_dbt_invalid"
      )
    }
    c(result[fields], list(config = result$output_config))
  })
}


#' Extension implementation helper
#'
#' Internal implementation interface for the DataRaft package family.
#' @usage NULL
#' @keywords internal
#' @export
#' @name dbt_source_catalog

dbt_source_catalog <- function(references, config = NULL) {
  rlang::local_error_call(rlang::caller_env())
  catalogs <- vapply(
    references,
    function(x) dbt_catalog_fingerprint(x$config),
    character(1)
  )
  if (length(unique(catalogs)) != 1L) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "All source bindings must belong to the same catalog.",
      "dr_dbt_invalid"
    )
  }
  if (
    !is.null(config) &&
      !identical(unname(catalogs[[1L]]), dbt_catalog_fingerprint(config))
  ) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "Sources belong to a different project catalog.",
      "dr_dbt_invalid"
    )
  }
  unname(catalogs[[1L]])
}


dbt_resolve_references <- function(references, lake) {
  rlang::local_error_call(rlang::caller_env())
  lapply(references, function(reference) {
    records <- dataraft.lake::dr_releases(lake, reference$asset)
    record <- records[
      records$release_id == reference$release_id,
      ,
      drop = FALSE
    ]
    runs <- dataraft.core::metadata_filter(
      lake,
      "runs",
      run_id = reference$run_id
    )
    if (
      nrow(record) != 1L ||
        nrow(runs) != 1L ||
        !identical(runs$asset[[1L]], reference$asset) ||
        !identical(runs$release_id[[1L]], reference$release_id) ||
        !identical(runs$status[[1L]], reference$status) ||
        !runs$status[[1L]] %in% c("published", "cached")
    ) {
      dataraft.core::abort(
        subclass = "dataraft_error_dbt",
        "A source does not match a successful run and exact release in the lake registry.",
        "dr_dbt_invalid"
      )
    }
    relation <- DBI::Id(
      catalog = "lake",
      schema = record$schema_name[[1L]],
      table = record$table_name[[1L]]
    )
    if (!DBI::dbExistsTable(lake$con, relation)) {
      dataraft.core::abort(
        subclass = "dataraft_error_dbt",
        "A pinned source release is no longer available in the lake.",
        "dr_dbt_invalid"
      )
    }
    list(
      asset = reference$asset,
      release_id = reference$release_id,
      run_id = reference$run_id,
      published_run_id = record$run_id[[1L]],
      status = reference$status,
      database = "lake",
      schema = record$schema_name[[1L]],
      table = record$table_name[[1L]]
    )
  })
}


dbt_binding_yaml <- function(resolved, name, catalog) {
  rlang::local_error_call(rlang::caller_env())
  schemas <- vapply(resolved, `[[`, character(1), "schema")
  if (length(unique(schemas)) != 1L) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "Each dbt source group needs one physical schema. Use dr_dbt_sources(..., name = ...) to declare separate groups for different layers.",
      "dr_dbt_invalid"
    )
  }
  tables <- lapply(seq_along(resolved), function(i) {
    ref <- resolved[[i]]
    list(
      name = names(resolved)[[i]],
      identifier = ref$table,
      description = paste("Published release of", ref$asset),
      config = list(
        meta = list(
          dataraft = ref[c(
            "asset",
            "release_id",
            "run_id",
            "published_run_id",
            "status"
          )]
        )
      )
    )
  })
  list(
    name = name,
    database = "lake",
    schema = unname(schemas[[1L]]),
    quoting = list(database = TRUE, schema = TRUE, identifier = TRUE),
    config = list(meta = list(dataraft = list(catalog = catalog))),
    tables = tables
  )
}


dbt_source_binding <- function(sources, name = "raw", config = NULL) {
  rlang::local_error_call(rlang::caller_env())
  references <- dbt_source_references(sources)
  catalog <- dbt_source_catalog(references, config)
  lake <- dataraft.lake::dr_connect_lake(
    config %||% references[[1L]]$config,
    read_only = TRUE
  )
  on.exit(dataraft.lake::dr_close_lake(lake), add = TRUE)
  resolved <- dbt_resolve_references(references, lake)
  dbt_binding_yaml(resolved, name, catalog)
}
