# Managed configuration is materialized only when a project executes.
dbt_managed_config <- function(config) {
  rlang::local_error_call(rlang::caller_env())
  if (
    !inherits(config, "dr_config") ||
      !identical(config$catalog$type, "duckdb") ||
      !identical(config$storage$type, "local") ||
      !config$backend %in% c("duckdb", "ducklake") ||
      isTRUE(config$read_only)
  ) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "lake must be a writable local DuckDB or DuckLake configuration. For other dbt adapters, supply profiles_dir instead.",
      "dr_dbt_invalid"
    )
  }
  invisible(config)
}


dbt_project_yaml <- function(project) {
  rlang::local_error_call(rlang::caller_env())
  dataraft.core::need("yaml")
  spec <- tryCatch(
    yaml::read_yaml(file.path(project$path, "dbt_project.yml")),
    error = identity
  )
  if (!is.list(spec) || inherits(spec, "error")) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "Cannot read dbt_project.yml as a YAML mapping.",
      "dr_dbt_invalid"
    )
  }
  spec
}


dbt_models_directory <- function(project, spec = dbt_project_yaml(project)) {
  rlang::local_error_call(rlang::caller_env())
  paths <- spec[["model-paths"]] %||% "models"
  if (
    !is.character(paths) ||
      !length(paths) ||
      anyNA(paths) ||
      any(!nzchar(paths)) ||
      any(grepl("\\{\\{|\\{%", paths))
  ) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "Managed source YAML needs a literal model-paths directory in dbt_project.yml.",
      "dr_dbt_invalid"
    )
  }
  path <- paths[[1L]]
  if (grepl("^(/|[A-Za-z]:|\\\\)|(^|[/\\\\])\\.\\.([/\\\\]|$)", path)) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "Managed source YAML must stay inside the project directory.",
      "dr_dbt_invalid"
    )
  }
  directory <- dataraft.core::absolute_path(file.path(project$path, path))
  if (!startsWith(paste0(directory, "/"), paste0(project$path, "/"))) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "Managed source YAML must stay inside the project directory.",
      "dr_dbt_invalid"
    )
  }
  directory
}


dbt_profile_output <- function(config, schema) {
  rlang::local_error_call(rlang::caller_env())
  attach <- list(path = config$catalog$path, alias = "lake")
  output <- list(
    type = "duckdb",
    path = ":memory:",
    database = "lake",
    schema = schema,
    threads = 1L
  )
  if (identical(config$backend, "ducklake")) {
    attach$path <- paste0("ducklake:", config$catalog$path)
    attach$options <- list(DATA_PATH = paste0(config$storage$path, "/"))
    output$extensions <- list("ducklake")
  }
  output$attach <- list(attach)
  output
}


dbt_prepare_managed <- function(project) {
  rlang::local_error_call(rlang::caller_env())
  if (is.null(project$lake)) {
    return(NULL)
  }
  dbt_managed_config(project$lake)
  spec <- dbt_project_yaml(project)
  profile <- spec$profile %||% spec$name
  if (
    !is.character(profile) ||
      length(profile) != 1L ||
      is.na(profile) ||
      !grepl("^[A-Za-z_][A-Za-z0-9_-]*$", profile)
  ) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "A managed project needs a literal profile name in dbt_project.yml.",
      "dr_dbt_invalid"
    )
  }
  target <- project$target %||% "dataraft"
  groups <- project$source_groups %||% list()
  catalog <- dbt_catalog_fingerprint(project$lake)
  invisible(lapply(groups, dbt_source_catalog, config = project$lake))
  # One read-only handle for all registry lookups, closed before any child starts.
  resolved <- list()
  if (length(groups)) {
    lake <- dataraft.lake::dr_connect_lake(project$lake, read_only = TRUE)
    resolved <- tryCatch(
      lapply(groups, dbt_resolve_references, lake = lake),
      finally = dataraft.lake::dr_close_lake(lake)
    )
  }
  bindings <- lapply(names(resolved), function(name) {
    dbt_binding_yaml(resolved[[name]], name, catalog)
  })
  directory <- dbt_models_directory(project, spec)
  destination <- file.path(directory, "dataraft_managed_sources.yml")
  marker <- "# Generated by dr_dbt_project."
  if (
    file.exists(destination) &&
      !identical(readLines(destination, n = 1L, warn = FALSE), marker)
  ) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "The managed source YAML is not package-owned; move or rename that file before running.",
      "dr_dbt_invalid"
    )
  }
  # Validate every source and file boundary before preparing any output file.
  schema <- if ("staging" %in% project$lake$layers) {
    "staging"
  } else if ("products" %in% project$lake$layers) {
    "products"
  } else {
    utils::tail(project$lake$layers, 1L)
  }
  profiles <- stats::setNames(
    list(list(
      target = target,
      outputs = stats::setNames(
        list(dbt_profile_output(project$lake, schema)),
        target
      )
    )),
    profile
  )
  list(
    profiles = profiles,
    profile = profile,
    target = target,
    destination = destination,
    source_yaml = c(
      marker,
      yaml::as.yaml(list(version = 2L, sources = bindings))
    ),
    source_bindings = resolved,
    catalog = catalog
  )
}


dbt_write_managed <- function(prepared, artifacts) {
  rlang::local_error_call(rlang::caller_env())
  profiles_dir <- file.path(artifacts, "profiles")
  dir.create(profiles_dir, recursive = TRUE, showWarnings = FALSE)
  yaml::write_yaml(prepared$profiles, file.path(profiles_dir, "profiles.yml"))
  directory <- dirname(prepared$destination)
  if (
    !dir.exists(directory) &&
      !dir.create(directory, recursive = TRUE, showWarnings = FALSE)
  ) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "Cannot create the managed dbt source directory.",
      "dr_dbt_io"
    )
  }
  temporary <- tempfile(".dataraft-managed-", tmpdir = directory)
  on.exit(unlink(temporary), add = TRUE)
  writeLines(prepared$source_yaml, temporary, useBytes = TRUE)
  if (!suppressWarnings(file.rename(temporary, prepared$destination))) {
    dataraft.core::abort(
      subclass = "dataraft_error_dbt",
      "Cannot replace the managed dbt source YAML; the previous file was preserved.",
      "dr_dbt_io"
    )
  }
  profiles_dir
}


#' @export
#' @noRd
#' @importFrom dataraft.core dr_inspect
dr_inspect.dr_dbt_project <- function(x, ...) {
  list(
    type = "dbt project",
    path = x$path,
    managed = !is.null(x$lake),
    target = x$target %||%
      if (!is.null(x$lake)) "dataraft" else "profile default",
    source_groups = lapply(x$source_groups %||% list(), function(group) {
      lapply(group, function(ref) {
        ref[c("asset", "release_id", "run_id", "status")]
      })
    }),
    status = "defined"
  )
}
